# Port of the gateway
server:
  port: 9000

# Gateway configuration
spring:
  cloud:
    gateway:
      routes:
        - id: user_route
          uri: lb://user-microservice
          predicates:
          - Path=/api/usr/**
          filters:
          - RewritePath=/api/usr(?<segment>), /user$\{segment}

        - id: job_route
          uri: lb://job-microservice
          predicates:
          - Path=/api/job/**
          filters:
          - RewritePath=/api(?<segment>/?), $\{segment}

management:
  endpoints:
    web:
      exposure:
        include: health,refresh

eureka:
  client:
    registerWithEureka: true
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER}
      #defaultZone: http://localhost:8761/eureka/
  instance:
    lease-renewal-interval-in-seconds: 30
